### ISSUE TITLE
brew install fails, curl returns 403

### ISSUE THREAD

**Issue by kaichengyan** [souffle-lang/homebrew-souffle#5]
`brew install` seems to fail because `curl`ing https://dl.bintray.com/souffle-lang/osx/souffle-2.0.2.tar.gz returns a 403.

```
$ brew reinstall souffle
==> Downloading https://dl.bintray.com/souffle-lang/osx/souffle-2.0.2.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "souffle"
Download failed: https://dl.bintray.com/souffle-lang/osx/souffle-2.0.2.tar.gz
```

**Comment by b-scholz** [comment]
I feel you have to upgrade souffle first and try to install it. Your brew cache may still have the old formula.

**Comment by kaichengyan** [comment]
Thank you for updating the formula! Homebrew is indeed able to download the tarball now. 🎉 

I am however getting another error with installing, but that's probably an issue for a different repo. Closing.

**Comment by b-scholz** [comment]
I noticed this as well - it is related to the bash-completion package (run install with -vd). We would need to disable the requirement to have bash-completion for MAC OS X or install it properly.
